# Generated by Django 6.0 on 2025-12-18 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nikkei225Data',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('changepercent', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snp500Data',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('changepercent', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),

    ]
