# Generated by Django 5.2.6 on 2025-12-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_portfolios_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
