# Generated by Django 6.0 on 2025-12-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_nikkei225data_snp500data_portfolios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nikkei225data',
            old_name='changepercent',
            new_name='changePercent',
        ),
        migrations.RenameField(
            model_name='snp500data',
            old_name='changepercent',
            new_name='changePercent',
        ),
    ]
