# Generated by Django 6.0 on 2025-12-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_changepercent_nikkei225data_changepercent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EuronextData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('changePercent', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SseData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.BigIntegerField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=20)),
                ('changePercent', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
    ]