# Generated by Django 6.0 on 2025-12-18 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_euronextdata_ssedata_portfolios_dax_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('investment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('FTSE_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('SNP500_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('NIKKEI225_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('EURONEXT_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('SSE_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('change_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
