# Generated by Django 6.0 on 2025-12-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_portfolios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EuronextData',
            new_name='Cac40Data',
        ),
    ]
