# Generated by Django 6.0 on 2025-12-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_euronextdata_cac40data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SseData',
            new_name='EuroStoxxData',
        ),
        migrations.RenameModel(
            old_name='Cac40Data',
            new_name='HsiData',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='EURONEXT_weight',
            new_name='EUROSTOXX_weight',
        ),
        migrations.RenameField(
            model_name='portfolios',
            old_name='SSE_weight',
            new_name='HSI_weight',
        ),
    ]
