# Generated by Django 6.0 on 2026-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_ssedata_eurostoxxdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='investment_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='daily', max_length=10),
        ),
    ]
